export const textStyles = {
  h1: {
    fontSize: "6.5625em",
    fontWeight: "700",
    lineHeight: "1",
    letterSpacing: "-0.02%",
    fontFamily: "heading",
  },
  h2: {
    fontSize: "4.125em",
    fontWeight: "200",
    lineHeight: "1",
    letterSpacing: "-0.01%",
    fontFamily: "heading",
  },
  h3: {
    fontSize: "3.25em",
    fontWeight: "300",
    lineHeight: "1.2",
    fontFamily: "heading",
  },
  h4: {
    fontSize: "1.625em",
    fontWeight: "400",
    lineHeight: "1.2",
    fontFamily: "heading",
  },
  h5: {
    fontSize: "1.375rem",
    fontWeight: "600",
    lineHeight: "1.2",
    fontFamily: "heading",
  },
  subtitle1: {
    fontSize: "1.0625rem",
    fontWeight: "500",
    lineHeight: "1.2",
    fontFamily: "heading",
  },
  subtitle2: {
    fontSize: "0.9375rem",
    fontWeight: "600",
    lineHeight: "1.2",
    fontFamily: "heading",
  },
  body1: {
    fontSize: "1rem",
    fontWeight: "400",
    lineHeight: "1.4",
    fontFamily: "body",
  },
  p: {
    fontSize: "1rem",
    fontWeight: "400",
    lineHeight: "1.4",
    fontFamily: "body",
  },
  body2: {
    fontSize: "0.875rem",
    fontWeight: "400",
    lineHeight: "1.4",
    fontFamily: "body",
  },
  button: {
    fontSize: "0.875rem",
    fontWeight: "700",
    lineHeight: "1",
    letterSpacing: "1%",
    fontFamily: "heading",
    textTransform: "uppercase",
  },
  caption: {
    fontSize: "0.75rem",
    fontWeight: "400",
    lineHeight: "1.1",
    fontFamily: "body",
  },
  overline: {
    fontSize: "0.625rem",
    fontWeight: "400",
    lineHeight: "1",
    letterSpacing: "0.15%",
    fontFamily: "body",
    textTransform: "uppercase",
  },
};
